version: "3.9"

services:
  db:
    container_name: django-postgres-react-db
    image: postgres
    volumes:
      - "./db/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: django-postgres-react-api
    build:
      context: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./api:/api"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db