version: "3.9"

services:
  db:
    container_name: django-postgres-react-db
    image: postgres
    restart: always
    volumes:
      - "./backend/db/data:/var/lib/postgresql/data"
    networks:
      - local-network
    ports:
      - "5432:5432"
    environment:
      # TODO: *** Change these to match your own database auth! ***
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: django-postgres-react-api
    build:
      context: ./backend/api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./backend/api:/api"
    networks:
      - local-network
    ports:
      - "8000:8000"
    environment:
      # TODO: *** Change these to match your own database auth! ***
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    container_name: django-postgres-react-frontend
    build:
      context: ./frontend/react
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/react:/home/node/app"

volumes:
  db:
    driver: local

networks:
  local-network:
    driver: bridge